### ISSUE TITLE
Error with Python 3.4 and subprocess.run

### ISSUE THREAD

**Issue by antonio-cortes-perez** [learningequality/ricecooker#77]
* ricecooker version: 0.5.8
* Python version: 3.4
* Operating System: Ubuntu 14.04

### Description
After importing 
from ricecooker.utils.html import download_file

and trying to run a chef, I got:
from subprocess import run
ImportError: cannot import name 'run'

The python doc says: "The run() function was added in Python 3.5; if you need to retain compatibility with older versions, see the Older high-level API section."

**Comment by benjaoming** [comment]
Additionally, a test needs to be written because we do test Python 3.4 with Travis+Tox, so it could be caught.

**Comment by ivanistheone** [comment]
The package  `css_html_js_minify` uses anglerfish, which doesn't work in Python 3.4:

```
(venv)ivan@engageny-demo:~/src/sushi-chef-engageny$ ./engageny_chef.py --reset
Traceback (most recent call last):
  File "./engageny_chef.py", line 26, in <module>
    from ricecooker.utils.html import download_file
  File "/home/ivan/src/sushi-chef-engageny/venv/lib/python3.4/site-packages/ricecooker/utils/html.py", line 7, in <module>
    from css_html_js_minify.minify import process_multiple_files, walk2list, Pool, cpu_count, partial
  File "/home/ivan/src/sushi-chef-engageny/venv/lib/python3.4/site-packages/css_html_js_minify/__init__.py", line 11, in <module>
    from .minify import (process_single_html_file, process_single_js_file,
  File "/home/ivan/src/sushi-chef-engageny/venv/lib/python3.4/site-packages/css_html_js_minify/minify.py", line 28, in <module>
    from anglerfish import (check_encoding, check_folder, make_logger,
  File "/home/ivan/src/sushi-chef-engageny/venv/lib/python3.4/site-packages/anglerfish/__init__.py", line 33, in <module>
    from anglerfish.make_beep import beep  # noqa
  File "/home/ivan/src/sushi-chef-engageny/venv/lib/python3.4/site-packages/anglerfish/make_beep.py", line 13, in <module>
    from subprocess import run
ImportError: cannot import name 'run'
```
The rest of `ricecooker` works fine with Py34. In particular all the current tests pass.

Not sure how to proceed: either we say ricecooker is only Py35+ or we remove the dependency on `css_html_js_minify`.
